Feat/fa locale
mastermunj/to-words pull request #216
Opened 2020-10-25 21:47 UTC by masihjahangiri

2020-10-26 12:16 UTC, mastermunj commented
Hi @masihjahangiri, a big thank you for raising the PR.

Please help take care of following points:

* Use the format of language code and country code for naming the locale file. e.g. `en-US`
* Add unit tests.
* Use npm instead of yarn

2020-10-31 14:05 UTC, masihjahangiri commented
Thanks @mastermunj. I fixed your points. please review again.

2020-11-06 03:17 UTC, masihjahangiri commented
@mastermunj Thanks for make this elegant library. May you review my MR to add Fa language to your package.

2020-11-06 12:14 UTC, mastermunj requested changes

2020-11-06 21:56 UTC, masihjahangiri commented on dist/to-words.js
> +                return require('./locales/fa').Locale;
@mastermunj Thanks for your notice, I updated it and built a repository.

2020-11-08 06:31 UTC, mastermunj approved these changes

2020-11-08 06:32 UTC, merged

2020-12-05 14:27 UTC, mastermunj commented
Hi @masihjahangiri, I am making changes in code to include several of Indian languages, however, I am not having challenge understanding the code you wrote for `fa-IR` locale.

I need your help in understanding the change you made and how the number system there works so that it becomes easier for me to navigate through the code for making the changes I need to make.

2020-12-05 19:48 UTC, masihjahangiri commented
Hi, @mastermunj sure. How can I help you?

2020-12-05 20:11 UTC, mastermunj commented
I'd appreciate if you can elaborate the changes done [here](https://github.com/mastermunj/to-words/pull/216/files?file-filters%5B%5D=.json&file-filters%5B%5D=.ts&file-filters%5B%5D=dotfile#diff-a187ddcd6925a702834b3287af6b121257823ba0b154834afb93c86e185c20c6R87-R186).

Also, the logic behind adding options and decimalLengthWordMapping [here](https://github.com/mastermunj/to-words/pull/216/files?file-filters%5B%5D=.json&file-filters%5B%5D=.ts&file-filters%5B%5D=dotfile#diff-138f0d4c704276147ddb7802c044f245faf979f38e3c49fb09ddaa468091dca0R22-R38).