Created Locale for en-GH
mastermunj/to-words pull request #517
Opened 2021-08-10 15:11 UTC by wocodes

Created test case for en-GH

Updated README file

2021-08-10 16:47 UTC, mastermunj commented
@wocodes Thank you for the PR.

Please help resolve the issues with tests.

2021-08-19 15:47 UTC, wocodes commented
@mastermunj This has been updated

2021-08-20 05:18 UTC, mastermunj requested changes

2021-08-20 05:18 UTC, mastermunj commented on package-lock.json
> +  "lockfileVersion": 1,
@wocodes We have moved on to lockfile version 2. You'd need to either remove package-lock.json from commits or upgrade your npm to ensure correct changes come in.

2021-08-21 10:28 UTC, wocodes commented
@mastermunj Thanks for the heads up. I've updated this PR. Kindly review

2021-08-24 04:16 UTC, merged

2021-08-24 04:16 UTC, mastermunj commented
Thank you!