feat(language): added support for dutch nl-SR language and currency
mastermunj/to-words pull request #805
Opened 2022-04-14 12:09 UTC by blue-predator

Please merge and release

2022-04-14 12:16 UTC, blue-predator commented
Seems 3 other languages test are not complete.
![image](https://user-images.githubusercontent.com/53546590/163388460-a6df1be9-7208-43ff-a7c6-5e071c687765.png)

2022-04-14 12:38 UTC, mastermunj requested changes

2022-04-14 12:38 UTC, mastermunj commented on src/ToWords.ts
> -        return enBd;
@blue-predator These changes could be the reason for test cases failing for en-BD, en-GB and tr-TR.

2022-04-14 12:38 UTC, mastermunj commented on src/ToWords.ts
> +    if (quotient === 1 && locale.config?.ignoreOneForWords) {
This also doesn't seem a needed change.

2022-04-14 13:20 UTC, blue-predator commented
> Seems 3 other languages test are not complete. ![image](https://user-images.githubusercontent.com/53546590/163388460-a6df1be9-7208-43ff-a7c6-5e071c687765.png)

Sorry it was my mistake, I'm rushing too much on this. I had overwritten the ToWords.ts with the one from v3 thinking they where the same. All is good now.
![image](https://user-images.githubusercontent.com/53546590/163394265-b477f4e6-cfb4-42b9-a030-2e352ee3f825.png)

2022-04-16 05:26 UTC, mastermunj approved these changes

2022-04-16 05:27 UTC, merged

2022-04-16 06:23 UTC, mastermunj commented
Thank you. Released 3.2.0.